name: Publish

on:
  push:
    branches:
      - main
    tags:
      - '*.*.*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Clean
        run: dotnet clean -c Release

      - name: Build
        run: dotnet build -c Release

      - name: Test
        run: dotnet test -c Release --no-build

      - name: Pack
        run: dotnet pack -c Release --no-build

      - name: Publish
        run: dotnet nuget push **/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }}
